// Run: node tools/logic-checks.mjs   (garment state rules, photo gallery data, photo base, shared preview SSR render)
import { createServer } from 'vite';
const v = await createServer({ server: { middlewareMode: true }, appType: 'custom', logLevel: 'error' });
const L = p => v.ssrLoadModule(p);
const G = await L('/src/pages/client/design-studio/garmentCatalog.js');
const S = await L('/src/pages/client/design-studio/designSerialization.js');
const D = await L('/src/pages/client/design-studio/designGallery.js');
const A = await L('/src/pages/client/design-studio/garmentAssets.js');
const Sh = await L('/src/pages/client/design-studio/dsShared.js');
const React = (await import('react')).default;
const { renderToString } = await import('react-dom/server');
const Prev = (await L('/src/components/DesignPreview.jsx')).default;
const out = []; const t = (n, c) => out.push((c ? 'PASS ' : 'FAIL ') + n);
const base = { category: 'School Uniform', garment: 'Polo Shirt', sleeve: 'Short', fit: 'female' };
t('pants null sleeve/fit', (c => c.sleeve === null && c.fit === null)(G.applyGarment(base, 'Pants')));
t('polo forced Short', G.applyGarment({ ...base, sleeve: 'Long' }, 'Polo Shirt').sleeve === 'Short');
const E0 = id => D.ENTRIES.find(d => d.id === id);
t('gallery = 35 photos only (20 original + 15 worn cutouts)', D.ENTRIES.length === 35 && D.ENTRIES.every(d => d.kind === 'photo') && D.ENTRIES.filter(d => d.source === 'worn').length === 15);
t('no template names as entries', !D.ENTRIES.some(d => ['Polo Shirt', 'Pants', 'Shorts', 'Skirt', 'Round Neck', 'Button-Down'].includes(d.name)));
t('metadata shape', D.ENTRIES.every(d => d.id && d.image && d.label && d.category && d.piece && 'gender' in d && 'sleeve' in d && 'garmentFamily' in d && typeof d.editable2D === 'boolean' && d.glb === null && d.source && d.status));
t('no photo has 3D', D.ENTRIES.every(d => !d.has3D));
t('statuses only reference/editable-2d', D.ENTRIES.every(d => ['reference', 'editable-2d'].includes(d.tier)));
t('search blazer = 8', D.filterDesigns({ q: 'blazer' }).length === 8);
t('search mandarin >= 3', D.filterDesigns({ q: 'mandarin' }).length >= 3);
t('filter medical = 2 scrub sets', D.filterDesigns({ category: 'medical' }).length === 2 && D.filterDesigns({ category: 'medical' }).every(d => d.piece === 'set'));
t('unisex has 1 photo (the embroidered polo)', D.facetCounts({}).gender.unisex === 1);
t('7 editable-2d photos (yellow blouse and polka-dot are reference-only)', D.ENTRIES.filter(d => d.editable2D).length === 7 && !E0('blouse-mandarin-yellow').editable2D && !E0('shirt-mandarin-polkadot').editable2D);
for (const d of D.ENTRIES) { const tg = D.openTarget(d, {}); t(`${d.id}: ${d.editable2D ? 'opens ' + tg?.garment : 'reference-only'}`, d.editable2D ? !!G.FAMILY_BY_NAME[tg.garment] : tg === null); }
t('assetFor Scrub Top Short front', !!A.assetFor('Scrub Top', 'Short', 'front'));
t('no asset for 3/4, back, T-Shirt', !A.assetFor('Scrub Top', '3/4', 'front') && !A.assetFor('Scrub Top', 'Short', 'back') && !A.assetFor('T-Shirt', 'Short', 'front'));
t('zonesFor photo base = [body]', JSON.stringify(Sh.zonesFor('Scrub Top', 'Short')) === '["body"]');
t('zonesFor 3/4 keeps vector zones', Sh.zonesFor('Scrub Top', '3/4').length > 1);
t('assetFor Mandarin Collar Short front = photo, 2 zones', (a => !!a && a.zones.join() === 'body,collar' && !!a.trim)(A.assetFor('Mandarin Collar', 'Short', 'front')));
t('Mandarin Collar Long is the BIR blouse photo; any back stays vector', A.assetFor('Mandarin Collar', 'Long', 'front')?.id === 'mandarin-blouse-bir-long' && !A.assetFor('Mandarin Collar', 'Short', 'back') && !A.assetFor('Mandarin Collar', 'Long', 'back'));
t('zonesFor mandarin photo = body,collar', Sh.zonesFor('Mandarin Collar', 'Short').join() === 'body,collar');
t('mandarin photo: single fit, no gender control', G.FAMILY_BY_NAME['Mandarin Collar'].fits.length === 1 && G.resolveFit('Mandarin Collar', 'male') === null);
t('housekeeping photo opens Mandarin Collar Short', (g => g?.garment === 'Mandarin Collar' && g.sleeve === 'Short')(D.openTarget(D.ENTRIES.find(d => d.id === 'scrub-set-housekeeping'), {})));
const E = id => D.ENTRIES.find(d => d.id === id);
t('housekeeping photo lands on the housekeeping asset', (g => A.assetFor(g.garment, g.sleeve, 'front', g.fit)?.id === 'mandarin-tunic-housekeeping')(D.openTarget(E('scrub-set-housekeeping'), {})));
t('yellow mandarin blouse is reference-only (no wrong base)', E('blouse-mandarin-yellow').tier === 'reference' && D.openTarget(E('blouse-mandarin-yellow'), {}) === null);
t('polka-dot long mandarin is reference-only (Long is now the BIR blouse, a different garment)', D.openTarget(E('shirt-mandarin-polkadot'), {}) === null && E('shirt-mandarin-polkadot').tier === 'reference');
t('women scrub photo -> women asset', (g => A.assetFor(g.garment, g.sleeve, 'front', g.fit)?.id === 'scrub-top-women-short')(D.openTarget(E('scrub-set-women-vneck'), {})));
t('men scrub photo -> men asset', (g => g.fit === 'male' && A.assetFor(g.garment, g.sleeve, 'front', g.fit)?.id === 'scrub-top-men-short')(D.openTarget(E('scrub-set-men-vneck'), {})));
t('sleeve filter the photo does not have is ignored, base unchanged', D.openTarget(E('scrub-set-housekeeping'), { sleeve: 'Long' })?.sleeve === 'Short');
t('unknown asset id -> null', A.assetById('nope') === null && A.assetById('mandarin-tunic-housekeeping')?.src.endsWith('.webp'));
t('photo bases are front-only', !A.hasBackView('Mandarin Collar', 'Short') && !A.hasBackView('Scrub Top', 'Short', 'male') && A.hasBackView('T-Shirt', 'Short') && !A.hasBackView('Mandarin Collar', 'Long') && !A.hasBackView('Round Neck', 'Short') && A.hasBackView('Round Neck', 'Long'));
const R = G.resolveTarget('Mandarin Collar', 'Short', 'male');
t('resolveTarget mandarin: photo, 2D only, no GLB, no fake fit', R.assetId === 'mandarin-tunic-housekeeping' && R.photo && R.glb === null && R.status === 'editable-2d' && R.fit === null);
t('resolveTarget polo: 2D+3D approx, never verified', (r => r.status === '2d-3d-approx' && !!r.glb)(G.resolveTarget('Polo Shirt', 'Short', 'female')));
t('resolveTarget Button-Down Long -> 2D only (GLB is short sleeve)', (r => r.glb === null && r.status === 'editable-2d')(G.resolveTarget('Button-Down', 'Long')));
t('resolveTarget unknown -> null', G.resolveTarget('Garbage') === null);
t('no current garment is verified (honest zero)', Object.keys(G.FAMILY_BY_NAME).every(g => G.resolveTarget(g, null, null).status !== '2d-3d' && !G.FAMILY_BY_NAME[g].verified3D));
t('statusFor supports a future verified asset', G.statusFor({ editable2D: true, has3D: true, verified3D: true }) === '2d-3d' && G.statusFor({ editable2D: true, has3D: true, verified3D: false }) === '2d-3d-approx' && G.statusFor({ editable2D: true, has3D: false, verified3D: true }) === 'editable-2d' && G.statusFor({ editable2D: false, has3D: true, verified3D: true }) === 'reference');
const sc = S.serializeDesign({ ...G.applyGarment(base, 'Mandarin Collar'), colors: { body: '#123456', collar: '#abcdef' }, overlays: [] });
const ph = renderToString(React.createElement(Prev, { cfg: sc, height: 220 }));
t('mandarin preview: one photo (front only), no vector svg', (ph.match(/<img/g) || []).length === 1 && !ph.includes('<svg') && ph.includes('mandarin-tunic-housekeeping'));
const ser = S.serializeDesign({ ...G.applyGarment(base, 'T-Shirt'), colors: { body: '#123456' }, overlays: [] });
let h = renderToString(React.createElement(Prev, { cfg: ser, height: 220 }));
t('studio cfg -> 2 silhouettes, no 3D toggle without WebGL', (h.match(/<svg/g) || []).length === 2 && !h.includes('Preview type'));
t('previewUrl -> img', renderToString(React.createElement(Prev, { cfg: ser, previewUrl: '/x.png' })).includes('src="/x.png"'));
t('null cfg no crash', renderToString(React.createElement(Prev, { cfg: null })).includes('No design preview'));
t('legacy garmentType no crash', typeof renderToString(React.createElement(Prev, { cfg: { garmentType: 'T-Shirt' } })) === 'string');
t('unknown garment no crash', typeof renderToString(React.createElement(Prev, { cfg: { garment: 'Garbage' } })) === 'string');
t('reference image', renderToString(React.createElement(Prev, { cfg: null, referenceImageUrl: '/ref.png' })).includes('/ref.png'));
for (const g of ['Pants', 'Skirt', 'Polo Shirt', 'T-Shirt', 'Scrub Top']) { const cfg = { ...G.applyGarment(base, g), colors: { body: '#123456' }, overlays: [] }; const r = S.deserializeDesign(JSON.parse(JSON.stringify(S.serializeDesign(cfg)))); const b = r.cfg ?? r; t(`roundtrip ${g}`, b.garment === g && b.sleeve === cfg.sleeve && b.fit === cfg.fit); }
// Studio picker: browsing a category never changes the design, picking a garment sets the category it was picked from.
const SG = await L('/src/pages/client/design-studio/selectGarment.js');
t('selectFamily passes the browsed category', (c => { let st = { ...base, category: 'School Uniform' }; SG.selectFamily(fn => { st = fn(st); }, G.familyFor('Scrub Top'), 'Medical / Scrubs'); return st.garment === 'Scrub Top' && st.category === 'Medical / Scrubs'; })());
t('selectFamily without a category keeps the current one', (c => { let st = { ...base, category: 'School Uniform' }; SG.selectFamily(fn => { st = fn(st); }, G.familyFor('Scrub Top')); return st.garment === 'Scrub Top' && st.category === 'School Uniform'; })());
// Personal artwork is a tagged image overlay: the tag survives serialize -> JSON -> deserialize, and the garment stays untouched.
{ const art = { type: 'Image', __logo: true, __artwork: true, __layerId: 'a1', __layerName: 'Artwork' };
  const cfg = { ...G.applyGarment(base, 'Scrub Top'), colors: { body: '#123456' } };
  const r = S.deserializeDesign(JSON.parse(JSON.stringify(S.serializeDesign(cfg, { overlays: [art], frontOverlays: [art], backOverlays: [] }))));
  const kept = JSON.stringify(r).includes('"__artwork":true');
  t('artwork tag survives save/restore', kept);
  t('artwork does not alter garment, sleeve or fit', r.cfg.garment === 'Scrub Top' && r.cfg.sleeve === cfg.sleeve && r.cfg.fit === cfg.fit); }
console.log(out.join('\n')); const f = out.filter(x => x.startsWith('FAIL')).length; console.log(`${out.length - f}/${out.length} passed`);
await v.close(); process.exit(f ? 1 : 0);

// ---- new worn-photo assets + GLB slots
const GS = await import(new URL('../src/pages/client/design-studio/glbSlots.js', import.meta.url));
const fsx = await import('node:fs'); const pathx = await import('node:path');
const pub = f => pathx.join(new URL('../public', import.meta.url).pathname, f);
t('all 15 worn photos have a cutout file', D.ENTRIES.filter(d => d.source === 'worn').every(d => fsx.existsSync(pub(d.image.slice(1)))));
t('every photo base file exists and ids are unique', (ids => ids.length === 5 && new Set(ids).size === 5)(['Scrub Top|Short', 'Scrub Top|Short', 'Mandarin Collar|Short', 'Mandarin Collar|Long', 'Round Neck|Short'].map((k, n) => { const [g, sl] = k.split('|'); const a = n === 1 ? A.assetFor(g, sl, 'front', 'male') : A.assetFor(g, sl, 'front', 'female'); return fsx.existsSync(pub(a.src.slice(1))) ? a.id : null; })));
t('BIR blouse photo -> Mandarin Collar Long base', (g => g.garment === 'Mandarin Collar' && g.sleeve === 'Long' && A.assetFor(g.garment, g.sleeve, 'front', g.fit)?.id === 'mandarin-blouse-bir-long')(D.openTarget(E('bir-blouse-trousers-blue'), {})));
t('fuchsia blouse photo -> Round Neck Short base', (g => g.garment === 'Round Neck' && A.assetFor(g.garment, g.sleeve, 'front', g.fit)?.id === 'round-neck-fuchsia-short')(D.openTarget(E('blouse-roundneck-fuchsia'), {})));
t('mustard blouse, blazers, dresses, polo, shirts: reference-only', ['blouse-roundneck-mustard', 'blazer-pinstripe-navy', 'dress-sheath-denim-blue', 'polo-red-claremont', 'shirt-two-tone-gpc', 'jack-shirt-two-tone', 'polo-barong-brown', 'peplum-set-navy'].every(id => E(id).tier === 'reference' && D.openTarget(E(id), {}) === null));
t('Round Neck Long stays vector, Round Neck has no GLB', !A.assetFor('Round Neck', 'Long', 'front') && G.resolveTarget('Round Neck', 'Short').glb === null && G.resolveTarget('Round Neck', 'Short').status === 'editable-2d');
t('GLB slots: every slot is empty (state none) and no GLB file exists for it', Object.values(GS.GLB_SLOTS).every(sl => sl.state === 'none' && sl.verification === null && !fsx.existsSync(pub(sl.file.slice(1)))));
t('GLB slots: every photo base has a slot, resolveTarget exposes it', ['scrub-top-women-short', 'scrub-top-men-short', 'mandarin-tunic-housekeeping', 'mandarin-blouse-bir-long', 'round-neck-fuchsia-short'].every(id => GS.glbSlotFor(id)) && G.resolveTarget('Mandarin Collar', 'Long').glbSlot?.id === 'mandarin-blouse-bir-long');
t('GLB slots: a slot never changes 3D status', G.resolveTarget('Mandarin Collar', 'Long').glb === null && G.resolveTarget('Mandarin Collar', 'Long').status === 'editable-2d');
t('15 worn photos each have a photo: slot', D.ENTRIES.filter(d => d.source === 'worn').every(d => GS.glbSlotFor(d.id)?.id === `photo:${d.id}`));
